module.exports = {
    MLAB_API_KEY: 'YOUR_API_KEY_HERE',
    LINE_CHANNEL_ID: 'YOUR_LINE_CHANNEL_ID',
    LINE_CHANNEL_SECRET: 'YOUR_LINE_CHANNEL_SECRET',
    LINE_CHANNEL_ACCESS_TOKEN: 'YOUR_LINE_CHANNEL_ACCESS_TOKEN'
}